### ISSUE TITLE
[BUG] Doesn't work for numbers greater than or 100000 (one hundred thousand)

### ISSUE THREAD

**Issue by yawboakye** [ohara-invent/intro_to_programming#2]
@ohara-invent Depending on the size of the number, either `extract_tens` or `extract_thousands` throws an exception similar to:

```
100000: ./fiw.rb:54:in `extract_tens': undefined method `+' for nil:NilClass (NoMethodError)
    from ./fiw.rb:29:in `extract_thousands'
    from ./fiw.rb:23:in `nums_to_words'
    from ./fiw.rb:7:in `block in main'
    from ./fiw.rb:4:in `each'
    from ./fiw.rb:4:in `main'
    from ./fiw.rb:130:in `<main>'
```

The case above is the exception for 100_000.

**Comment by yawboakye** [comment]
@ohara-invent I took a look at the implementation of `extract_tens` (starting on [L47](https://github.com/ohara-invent/intro_to_programming/blob/ab9a2fb3e95a34915c5c011bf9db7945ace3f8dd/092716/fiw.rb#L47)):

``` ruby
def extract_tens(number)
  tens = ["", "ten", "twenty", "thirty", "forty", "fifty", "sixty", "seventy", "eighty", "ninety"]
    if (number < 10)
      return extract_ones(number)
    elsif (number < 20)
      return extract_teens(number)
    elsif (number <= 100)
      return tens[number / 10] + " " + extract_ones(number % 10)
    end
end
```

if `number` is equal to `100` going into the `elsif number <= 100` branch, then `number/10` will be equal to `10`, and that's what you use to index the `tens` array. But the last index of `tens` is `9` not `10`, and so the program fails at that point. Please see if that's the case.
